use_frameworks!

target 'DeepStreamIOS_Example' do
  pod 'DeepStreamIOS', :path => '../'

  target 'DeepStreamIOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
